### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by jsmmo** [kaythinks/kayphpframework#1]
There are some objects like `(new Database)` which could be created only once so its faster.

There fore the Database class could be make Singleton which would be a fast solution, but future wise it better to get some DI concept into this project. What is your preferred solution? A DI container? Just constructor DI? or a ObjectManager?

Target is that these lines dont create a PDO object everytime:

`return (new Database)->method`

**Comment by kaythinks** [comment]
I would definitely look into it. Thanks once again.

**Comment by kaythinks** [comment]
Solved.

**Comment by PurHur** [comment]
Doesnt look any different now?
https://github.com/kaythinks/kayphpframework/blob/master/app/Models/Model.php

**Comment by kaythinks** [comment]
I am talking about the Dependency Injection Container. The Model class implementation works since the model only calls the DB once. e.g User::all() , User::find(11 )e.t.c

**Comment by kaythinks** [comment]
> Doesnt look any different now?
> https://github.com/kaythinks/kayphpframework/blob/master/app/Models/Model.php
I am talking about the Dependency Injection Container. The Model class implementation works since the model only calls the DB once. e.g User::all() , User::find(11 )e.t.c

**Comment by PurHur** [comment]
Here you are using multiple SQL queries in one Action:
Also the redis lines are the same here:
https://github.com/kaythinks/kayphpframework/blob/master/app/Controllers/HomeController.php#L215

**Comment by kaythinks** [comment]
I get you. For the redis object, it can be instantiated in the construct method and then be referenced by a property. Thanks for that. For the model, each call opens and closes the DB e.g calling User::all() will close the DB connection when the Data is gotten.

**Comment by kaythinks** [comment]
> Here you are using multiple SQL queries in one Action:
> Also the redis lines are the same here:
> https://github.com/kaythinks/kayphpframework/blob/master/app/Controllers/HomeController.php#L215
I get you. For the redis object, it can be instantiated in the construct method and then be referenced by a property. Thanks for that. For the model, each call opens and closes the DB e.g calling User::all() will close the DB connection when the Data is gotten.
