### ISSUE TITLE
Support multiple browser tabs

### ISSUE THREAD

**Issue by jsmmo** [kaythinks/kayphpframework#2]
Currently its not possible to browse different forms in different tabs at the same time.

This is because there is only one token valid each time. It could be changed to a static configurable salt with a lifetime for each token. 

https://github.com/kaythinks/kayphpframework/blob/ceed92d629cf9cf16d37e473a3c6c4c6bd62aa49/app/Systems/Helpers.php#L14

**Comment by kaythinks** [comment]
This would be looked into. I also don't mind if you can update and make a PR. Thanks.
